- name: Create user for Kafka
  user:
    name: kafka
    shell: /bin/nologin
    state: present

- name: Create user for Zookeeper
  user:
    name: zookeeper
    shell: /bin/nologin
    state: present

- name: Install Java package
  apt:
    name: openjdk-8-jdk
    state: present
    update_cache: yes

- name: Check Kafka is exist
  stat:
    path: '/opt/{{ kafka_distr }}'
  register: kafka_exists

- name: Install Kafka
  block:
    - name: Download Kafka distibution
      get_url: 
        url: '{{ kafka_url }}'
        dest: /tmp

    - name: Unpacking archive with Kafka distribution
      unarchive:
        src: /tmp/{{ kafka_archive }}
        dest: /opt
        remote_src: yes

    - name: Delete archive with Kafka distribution
      file:
        path: '/tmp/{{ kafka_archive }}'
        state: absent

    - name: Create symlink for install Kafka
      file:
        src: '/opt/{{ kafka_distr }}'
        dest: /opt/kafka
        state: link
  when: kafka_exists.stat.exists == false
  block:
  hosts: broker2
- name: Create topic logs directory for Kafka
  file:
    path: /tmp/lib/kafka/kafka-logs
    state: directory
    group: '{{ kafka_group }}'
    owner: '{{ kafka_user }}'
    mode: 0755

- name: Create var/lib directory for Kafka
  file:
    path: /var/lib/kafka
    state: directory
    group: '{{ kafka_group }}'
    owner: '{{ kafka_user }}'
    mode: 0755

- name: Create var/log directory for Kakfa
  file:
    path: /var/log/kafka
    state: directory
    group: '{{ kafka_group }}'
    owner: '{{ kafka_user }}'
    mode: 0755

- name: Create var/lib directory for Zookeeper
  file:
    path: /var/lib/zookeeper
    state: directory
    group: '{{ zookeeper_group }}'
    owner: '{{ zookeeper_user }}'
    mode: 0755

- name: Create var/log directory for Zookeeper
  file:
    path: /var/log/zookeeper
    state: directory
    group: '{{ zookeeper_group }}'
    owner: '{{ zookeeper_user }}'
    mode: 0755

- name: configure systemd zookeeper
  template:
    src: zookeeper.service.j2
    dest: /lib/systemd/system/zookeeper.service
    group: '{{ zookeeper_group }}'
    owner: '{{ zookeeper_user }}'
    mode: 0755
  notify: Restart Zookeeper service

- name: configure systemd kafka
  template:
    src: kafka.service.j2
    dest: /lib/systemd/system/kafka.service
    group: '{{ kafka_group }}'
    owner: '{{ kafka_user }}'
    mode: 0755
  notify: Restart Kafka service

- name: Restart systemd
  systemd:
    daemon_reload: yes
  become: true

# - name: Start Zookeeper service
#   service:
#       name: zookeeper
#       state: started
#       enabled: true 
#   become: yes

# - name: Wait for Zookeeper to start
#   pause:
#     seconds: 5

# - name: Start Kafka service
#   service:
#       name: kafka
#       state: started
#       enabled: true
#   become: yes