apiVersion: v1
kind: Service
metadata:
  name: hp-svc
  namespace: {{ .Values.meta.namespace }}
  labels:
    project: {{ .Values.meta.matchLabel }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.image.port }}
      targetPort: {{ .Values.image.port }}
      nodePort: {{ .Values.service.port }}
      name: hello-page
  selector:
    project: {{ .Values.meta.matchLabel }}